version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - '8000:8000'
    depends_on:
      - ml

  ml:
    build: ./ml
    ports:
      - '5000:5000'